### ISSUE TITLE
Enabling IOMMU disconnects USB devices

### ISSUE THREAD

**Issue by notgarette** [foxlet/vmra1n#1]
FX 8350
RX 480
MSI FXA990 GD80v2.2

Every time I enable IOMMU in my BIOS than when Ubuntu starts my USB devices get disconnected. iPhone stops charging, keyboard, mouse and microphone lights turn off and no longer send inputs.

**Comment by ann0see** [comment]
I think that’s intended.

**Comment by notgarette** [comment]
Well, okay. So is there nothing I can do? How can I reconnect them?

**Comment by foxlet** [comment]
If USB gets disconnected after rebinding, that is normal. If you're limited to only one controller, you have to remote in through VNC.

**Comment by notgarette** [comment]
After I click “Ubuntu” to boot into Ubuntu is when everything is disconnected. I can’t type my password to login or get further than that.

**Comment by foxlet** [comment]
Do you have any other kernel flags set in GRUB?

**Comment by notgarette** [comment]
The only thing I've done with GRUB was setting the iommu flags. https://pastebin.com/xJPq4xJp

**Comment by foxlet** [comment]
Try remove the `iommu=pt` flag, just keeping `amd_iommu=on`.

**Comment by notgarette** [comment]
No luck with that. What else should I try? Thanks for the help so far.

**Comment by notgarette** [comment]
I solved the issue. I had to update my BIOS, but the update tool was detecting my current BIOS as being newer than the newest BIOS. Had to hack together the BIOS to trick the installer. Thanks for the help though!

**Comment by foxlet** [comment]
Good to know the BIOS was an issue, I'll put that up on notes.
